FROM gcr.io/google-containers/kube-apiserver-amd64:v1.13.1
FROM gcr.io/google-containers/kube-controller-manager-amd64:v1.13.1
FROM gcr.io/google-containers/kube-scheduler-amd64:v1.13.1
FROM gcr.io/google-containers/kube-proxy-amd64:v1.13.1
FROM gcr.io/google-containers/pause:3.1
FROM gcr.io/google-containers/etcd-amd64:3.2.24
FROM gcr.io/google-containers/coredns:1.2.6
MAINTAINER storm